[Variables]

; ----------------------------------------- Group 1

GroupName1 =Shortcuts

Group1Name1=
Group1Path1=

Group1Name2=
Group1Path2=

Group1Name3=
Group1Path3=

Group1Name4=
Group1Path4=

; ----------------------------------------- Group 2

GroupName2 =Links

Group2Name1=/r/AndroidThemes
Group2Path1=

Group2Name2=/r/Rainmeter
Group2Path2=

Group2Name3=DeviantArt
Group2Path3=

Group2Name4=
Group2Path4=

; ----------------------------------------- Group 3

GroupName3 =Actions

Group3Name1=Rainmeter
Group3Path1=

Group3Name2=Logs
Group3Path2=

Group3Name3=Refresh All
Group3Path3=

Group3Name4=
Group3Path4=

; ----------------------------------------- Group 4

GroupName4 =

Group4Name1=
Group4Path1=

Group4Name2=
Group4Path2=

Group4Name3=
Group4Path3=

Group4Name4=
Group4Path4=

; ----------------------------------------- Group 5

GroupName5 =

Group5Name1=
Group5Path1=

Group5Name2=
Group5Path2=

Group5Name3=
Group5Path3=

Group5Name4=
Group5Path4=